### ISSUE TITLE
only http://localhost:8080/v1 works

### ISSUE THREAD

**Issue by sranso** [endpoints/example#10]
after running `npm install` and `npm start`
only http://localhost:8080/v1 works -- all the other routes return `Cannot GET <route>`

<3

**Comment by ashleygwilliams** [comment]
hi sarah! i can't reproduce your bug. http://localhost:8080/v1/authors works for me after a clean `clone`, `npm install`, and `npm start`. can you be more specific about the routes/errors you are seeing?

**Comment by tkellen** [comment]
I think I might know what the issue is--I never updated the links in the readme after we added the v1 namespace.

**Comment by ashleygwilliams** [comment]
that's it  @tkellen ! want me to submit a PR? @sranso wanna submit a PR?

**Comment by tkellen** [comment]
ya! or just push a fix to master?

**Comment by sranso** [comment]
yeah thanks @tkellen and @ashleygwilliams ! just seeing all this. <3 it.
