### ISSUE TITLE
Rename to `endpoints-example`

### ISSUE THREAD

**Issue by jamesplease** [endpoints/example#12]
`example` is too generic!

**Comment by tkellen** [comment]
Just added you as a collab on this org. Rename it however you like!

This will need to be updated too:
http://jsonapi.org/implementations/#examples

:p

**Comment by jamesplease** [comment]
@ashleygwilliams what do you think? I put all of my repos in one folder, `webdev`, so I'd rather it be a lil bit more specific so I can locate it down the road.

Also don't want to come in and go about renaming this project that y'all have worked so hard on, though!

**Comment by ashleygwilliams** [comment]
heyyy @jmeas - so i nest my projects in project directories so this doesn't affect me, but i think your case is compelling. :+1: to rename

**Comment by jamesplease** [comment]
Mmk, cool! Done  ~ ~ ~
