### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jamesplease** [endpoints/example#16]
This is maybe the easiest way to set up a fully functional JSON API-compliant API – with data – which can be useful when demonstrating **other** libraries that consume JSON APIs.

For instance, I'm learning the [Orbit.js](https://github.com/orbitjs/orbit.js) library, which (among other things) comes with out-of-the-box support for JSON API. To help with my learnin', I'm building [a repository of examples](https://github.com/jmeas/orbit-examples) that demonstrate the features. I'd like to require in the `endpoints-example` repo so that I can transparently start up this API from within that repo.

Thoughtz?

**Comment by ashleygwilliams** [comment]
I both see no problem with it, and also think it's a good idea.

This does re-bring up the idea of having an endpoints generator script a la [rails generate](http://guides.rubyonrails.org/command_line.html#rails-new)
