### ISSUE TITLE
Shouldnt your relationship links have the full path?

### ISSUE THREAD

**Issue by krzkrzkrz** [endpoints/example#19]
Shouldnt your relationship links have the full path? At http://jsonapi.org/format the example links look like:

```
http://example.com/articles/1/relationships/author
http://example.com/articles/1/author
```

Your relationship end points don't include `http://some-domain.com`. Or, doesn't matter?

**Comment by jamesplease** [comment]
ping @tkellen. I'm also curious to know the answer!

**Comment by tkellen** [comment]
JSON-API doesn't require this, but you could specify it on your controller's [`baseUrl` property](https://github.com/endpoints/endpoints-example/blob/master/src/classes/api.js#L14) if you wanted to.
