### ISSUE TITLE
Please add `create`, `update` and `destroy` examples

### ISSUE THREAD

**Issue by tenzan** [endpoints/example#25]
Please add `create`, `update` and `destroy` examples as well under **Setup Instructions** in the repo.

Thanks.

**Comment by jamesplease** [comment]
Are these not already in the example? For instance, [here](https://github.com/endpoints/endpoints-example/blob/ccc0e72794f5eda9bd3c89c7136021f7f8591d26/src/modules/books/routes.js).

**Comment by tenzan** [comment]
Unfortunately that's not giving how would I do in the browser.
In the README file there's several examples shown except the above 3 I'm asking for...

**Comment by tkellen** [comment]
@tenzan I believe what you're looking for is the documentation from http://jsonapi.org

**Comment by tenzan** [comment]
Hi @tkellen . I know that site.

What I meant is, in REAME file you have examples like:

```
http://localhost:8080/v1/authors
http://localhost:8080/v1/authors/1
http://localhost:8080/v1/authors/?filter[id]=1,2
```

So, my question was why don't you put also examples same way for `create`, `update` and `destroy` actions...

**Comment by tkellen** [comment]
No good reason, I suppose. I'd love a PR for this if you'd be willing!
