### ISSUE TITLE
For many-to-many relations, which one to use: morphMany or belongsToMany ?

### ISSUE THREAD

**Issue by tenzan** [endpoints/example#26]
Which is correct?

`return this.morphMany(require('../tags/model'), 'posts_tags');`

or

`return this.belongsToMany(require('../tags/model'), 'posts_tags');`

**Comment by jamesplease** [comment]
Endpoints is just a layer on top of [Bookshelf](http://bookshelfjs.org/), so answers to questions like this are available in the Bookshelf docs. [Here are the many-to-many docs](http://bookshelfjs.org/#many-to-many), where you can find your answer!

**Comment by tenzan** [comment]
Oops. Thanks. :)

**Comment by jamesplease** [comment]
No problem! : ]
