### ISSUE TITLE
published_before, published_after examples don't work

### ISSUE THREAD

**Issue by bmac** [endpoints/example#7]
[http://localhost:8080/books?published_after=1990-01-01](http://localhost:8080/books?published_after=1990-01-01) returns everything
[http://localhost:8080/books?filter[published_after]=1990-01-01](http://localhost:8080/books?filter[published_after]=1990-01-01) returns nothing

Same story for `published_before`

**Comment by tkellen** [comment]
Looks like the values are being passed as arrays rather than strings, so the comparison is failing.  I'll have a fix up in a minute.

**Comment by tkellen** [comment]
Resolved in https://github.com/endpoints/endpoints/commit/9f6c8f7fb63630f297a743b40b545d9a8da17963 (re-installing should do the trick)
