### ISSUE TITLE
chapters schema links to author not book?

### ISSUE THREAD

**Issue by ashleygwilliams** [endpoints/example#8]
curious as to why this is author and not book if a chapter belongs to a book? is it that a chapter has authors through book? why would book also not be included here? thanks!

https://github.com/endpoints/example/blob/master/src/modules/chapters/schema.js#L14-L18

**Comment by tkellen** [comment]
That's a bug. The schema validation stuff has not been thoroughly vetted. I'd love a PR to fix this!

**Comment by ashleygwilliams** [comment]
sure thing @tkellen. i'll do it later today.
